
name: Board Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  board-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run the board validation script
        run: |
          pip install -r requirements.txt
          python validateAllBoards.py --skip-autorepair --skip-update-dates --skip-mirror-validation --skip-download-validation --skip-music-uniqueness-validation
        working-directory: ./_scripts
